### ISSUE TITLE
'package:flutter/src/material/app.dart': Failed assertion: line 213 pos 15: 'data != null': is not true

### ISSUE THREAD

**Issue by vinitfractal** [flutter/friendlychat-steps#70]
I am new to flutter. I was referring to the flutter tutorial of [VoidRealms](https://www.youtube.com/watch?v=_vJZsdCC2EU&index=24&list=PLUbFnGajtZlX9ubiLzYz_cw92esraiIBi) It was working fine. Then I unplugged my mobile and again checked then the following error was shown.
**main.dart**
```
import 'package:flutter/material.dart';
import 'package:my_app/settings.dart';
import 'package:my_app/login.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _title;
  Widget _screen;
  Settings _settings;
  Login _login;
  bool _authenticated;

  _MyAppState() {
    _login = new Login(onSubmit: () {
      _onSubmit();
    });
    _settings = new Settings();
    _screen = _login;
    _authenticated = false;
  }

  void _goHome() {
    setState(() {
      if (_authenticated == true) {
        _screen = _settings;
      } else {
        _screen = _login;
      }
    });
  }

  void _logout() {
    print("Logout");
    _setauthentication(false);
  }

  void _onSubmit() {
    print(_login.username + ' ' + _login.password);
    if (_login.username == 'user' && _login.password == 'pass') {
      _setauthentication(true);
    }
  }

  void _setauthentication(bool auth) {
    setState(() {
      if (auth == true) {
        _screen = _settings;
        _title = "Welcome";
        _authenticated = true;
      } else {
        _screen = _login;
        _title = "Please Login";
        _authenticated = false;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: _title,
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("My app"),
          actions: <Widget>[
            new IconButton(
                icon: new Icon(Icons.home),
                onPressed: () {
                  _goHome();
                }),
            new IconButton(
                icon: new Icon(Icons.exit_to_app),
                onPressed: () {
                  _logout();
                }),
          ],
        ),
        body: _screen,
      ),
    );
  }
}
```

**Login.dart**

```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/foundation.dart';

class Login extends StatelessWidget {
  const Login({
    Key key,
    @required this.onSubmit,
  }) : super(key: key);

  final VoidCallback onSubmit;

  static final TextEditingController _user = new TextEditingController();
  static final TextEditingController _pass = new TextEditingController();

  String get username => _user.text;
  String get password => _pass.text;

  @override
  Widget build(BuildContext context) {
    return new Column(
      children: <Widget>[
        new TextField(
          controller: _user,
          decoration: new InputDecoration(hintText: "Enter a Username"),
        ),
        new TextField(
          controller: _pass,
          decoration: new InputDecoration(hintText: "Enter a Password"),
          obscureText: true,
        ),
        new RaisedButton(
          child: new Text("Submit"),
          onPressed: onSubmit,
        )
      ],
    );
  }
}

```
**Settings.dart**

```
import 'package:flutter/material.dart';

class Settings extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: new Text("Settings here"),
    );
  }
}
```

**Flutter Doctor**

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.15063], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 32-bit edition (version 1.23.1)
[√] Connected devices (1 available)

**Flutter run**

I/FlutterActivityDelegate(23963): onResume setting current activity to this
I/flutter (23963): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23963): The following assertion was thrown building MyApp(dirty, state: _MyAppState#486ef):
I/flutter (23963): 'package:flutter/src/material/app.dart': Failed assertion: line 146 pos 15: 'title != null': is not
I/flutter (23963): true.
I/flutter (23963):
I/flutter (23963): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23963): more information in this error message to help you determine and fix the underlying cause.
I/flutter (23963): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (23963):   https://github.com/flutter/flutter/issues/new
I/flutter (23963):
I/flutter (23963): When the exception was thrown, this was the stack:
I/flutter (23963): #2      new MaterialApp (package:flutter/src/material/app.dart)
I/flutter (23963): #3      _MyAppState.build (file:///D:/my_app/lib/main.dart:70:16)
I/flutter (23963): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter (23963): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter (23963): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (23963): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (23963): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (23963): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (23963): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (23963): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23963): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter (23963): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter (23963): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter (23963): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter (23963): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter (23963): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter (23963): #18     runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter (23963): #19     main (file:///D:/my_app/lib/main.dart:9:16)
I/flutter (23963): #20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (23963): #21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (23963): (elided 2 frames from class _AssertionError)
I/flutter (23963): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/OpenGLRenderer(23963): ProgramCache.generateProgram: 34359738369
I/SurfaceView(23963): updateWindow -- setFrame, this = io.flutter.view.FlutterView{9bebc95 VFE...... .F...... 0,0-720,1280}
Syncing files to device vivo 1713...                         7.0s

**Comment by vinitfractal** [comment]
The error was is in the **_title** area,
class _MyAppState extends State<MyApp> {
  **String _title;** -- It must be given a value
  Widget _screen;
  Settings _settings;
  Login _login;
  bool _authenticated;

Once the material app is called, the title is null, So it produced an error.
